[env:c5tako]
board = esp32c5
; Keep Launcher's inherited patched key-boot SDK packages.
board_build.arduino.memory_type = qio_qspi
board_build.psram_type = qspi
board_build.partitions = boards/c5tako/partitions.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 1572864
build_src_filter = ${env.build_src_filter} +<../boards/c5tako>
build_flags =
    ${env.build_flags}
    -DBOARD_HAS_PSRAM=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DDEVICE_NAME='"C5TAKO"'
    -DOTA_TAG='"C5TAKO"'
    -DHAS_5_BUTTONS=1
    -DLAUNCHER_GPIO_KEYS='{{"OK", 4}}'
    -DROTATION=0
    -DPREV_BTN=23
    -DNEXT_BTN=0
    -DUP_BTN=24
    -DDW_BTN=28
    -DSEL_BTN=4
    -DBTN_ACT=LOW
    -DBUZZ_PIN=3
    -DBAT_VOLT_PIN=6
    -DBAT_VOLT_PIN_EN=26
    -DCC1101_CS=2
    -DLED=27
    -DLED_ON=LOW
    -DLED_OFF=HIGH
    -DUSE_ARDUINO_GFX=1
    -DTFT_DATABUS_N=0
    -DTFT_DISPLAY_DRIVER_N=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_BL=25
    -DTFT_RST=-1
    -DTFT_DC=1
    -DTFT_MISO=9
    -DTFT_MOSI=10
    -DTFT_SCLK=8
    -DTFT_CS=7
    -DTOUCH_CS=-1
    -DTFT_IPS=1
    -DTFT_RGB_ORDER=TFT_RGB
    -DTFT_SPI_MODE=3
    -DTFT_WRITE_FREQ=40000000
    -DTFT_COL_OFS1=0
    -DTFT_ROW_OFS1=0
    -DTFT_COL_OFS2=0
    -DTFT_ROW_OFS2=80
    -DSDCARD_CS=5
    -DSDCARD_SCK=TFT_SCLK
    -DSDCARD_MISO=TFT_MISO
    -DSDCARD_MOSI=TFT_MOSI
lib_ignore =
    SensorLib
    XPowersLib
